#!/bin/bash
# personal script of Ped to launch "#CSpect" emulator with the "tbblue.mmc" (or first argument is image filename)
if [[ -s "$1" ]]; then
  MMCFILE="$1"
  shift
else
  MMCFILE=tbblue.mmc
fi
MONO_IOMAP=all mono `readlink ~/.local/bin/CSpect.exe` -analytics -tv -zxnext -s28 -w4 -nextrom -mmc="$MMCFILE" "$@"
