#!/bin/bash
# Run some snapshot file in ZESERUse emulator, which requires to be run from it's home dir.
# The directories are of my local installation, if there will be more linux users of this
# script, it should me moved into some environment variables like $ZXN_TESTS_ZESERUSE_DIR
RUN_SNA_FILE=`readlink -f "$1"` && \
SNA_PATH="${RUN_SNA_FILE%${RUN_SNA_FILE##*/}}" && \
[[ -s "$SNA_PATH/bpx.ini" ]] && breakpoints=`cat "$SNA_PATH/bpx.ini"` || breakpoints="" && \
cd ~/zx/ZEsarUX/ZEsarUX-current/ && \
./zeseruse --noconfigfile --vo sdl --ao pulse --machine tbblue --realvideo --tbblue-legacy-border --tbblue-legacy-hicolor --zoom 1 --enabletimexvideo --tbblue-fast-boot-mode --sna-no-change-machine --enable-esxdos-handler --nosplash --disablefooter --nowelcomemessage --quickexit --disabletooltips --forcevisiblehotkeys --disablemultitaskmenu --esxdos-root-dir "$SNA_PATH" "$RUN_SNA_FILE" $breakpoints
# the "readlink" will produce full path of provided argument, so the emulator will find it
# --enable-breakpoints --set-breakpoint 1 "PC=60F5h AND B=1Ch"
