#!/bin/bash
# Run some snapshot file in ZESERUse emulator, auto-appending breakpoints file "bpx.ini" if it exists
# keys 167/168 are PAGE_UP/PAGE_DOWN as those are better choice on my notebook for joystick fires, for --joystickemulated Kempston
if [[ -n "$1" ]]; then
  RUN_SNA_FILE=`readlink -f "$1"` && \
  SNA_PATH="${RUN_SNA_FILE%${RUN_SNA_FILE##*/}}" && \
  [[ -s "$SNA_PATH/bpx.ini" ]] && breakpoints=`cat "$SNA_PATH/bpx.ini"` || breakpoints=""
  shift
else
  RUN_SNA_FILE=""
  breakpoints=""
fi
zeseruse --noconfigfile --nologo --vo sdl --ao pulse --enable-esxdos-handler --nosplash --disablefooter --nowelcomemessage --disabletooltips --forcevisiblehotkeys --disablemultitaskmenu --joyfire1byutilskey 167 --joyfire2byutilskey 168 "$RUN_SNA_FILE" $breakpoints "$@"
# the "readlink" will produce full path of provided argument, so the emulator will find it
# --enable-breakpoints --set-breakpoint 1 "PC=60F5h AND B=1Ch"
