#!/bin/bash
# Run some snapshot file in ZEsarUX emulator, auto-appending breakpoints file "bpx.ini" if it exists
[[ -s "bpx.ini" ]] && breakpoints=`cat "bpx.ini"` || breakpoints=""
zesarux --noconfigfile --disablebetawarning "9.2-B1" --vo sdl --ao pulse --machine tbblue --realvideo --tbblue-legacy-border --tbblue-legacy-hicolor --zoom 1 --enabletimexvideo --tbblue-fast-boot-mode --sna-no-change-machine --enable-esxdos-handler --disable-autoframeskip --nosplash --disablefooter --nowelcomemessage --quickexit --disabletooltips --forcevisiblehotkeys --disablemultitaskmenu "$@" $breakpoints
# --enable-breakpoints --set-breakpoint 1 "PC=60F5h AND B=1Ch"

# command line of SevenFFF (shows some other possibilities):
#zesarux.exe --noconfigfile --machine tbblue --realvideo --enabletimexvideo --frameskip 0 --disable-autoframeskip --nosplash --nowelcomemessage --quickexit --gui-style "ZXSpectr" --def-f-function F4 "HardReset" --def-f-function F10 "ExitEmulator" --tbblue-fast-boot-mode --sna-no-change-machine --enable-esxdos-handler --esxdos-root-dir "C:\Spectron2084\sd" "C:\Spectron2084\bin\Spectron2084.sna"
