#!/bin/sh
# Run some snapshot file in ZEsarUX emulator, which requires to be run from it's home dir.
# The directories are of my local installation, if there will be more linux users of this
# script, it should me moved into some environment variables like $ZXN_TESTS_ZESARUX_DIR
RUNSNAFILE=`readlink -f $1` && cd ~/zx/ZEsarUX/ZEsarUX-current/ && ./zesarux --noconfigfile --vo sdl --ao sdl --machine tbblue --realvideo --zoom 1 --enabletimexvideo --tbblue-fast-boot-mode --sna-no-change-machine --enable-esxdos-handler --nosplash --disablefooter --nowelcomemessage --quickexit --disabletooltips --forcevisiblehotkeys --disablemultitaskmenu $RUNSNAFILE
# the "readlink" will produce full path of provided argument, so the emulator will find it
# --enable-breakpoints --set-breakpoint 1 "PC=60F5h AND B=1Ch"

# command line of SevenFFF (shows some other possibilities):
#zesarux.exe --noconfigfile --machine tbblue --realvideo --enabletimexvideo --frameskip 0 --disable-autoframeskip --nosplash --nowelcomemessage --quickexit --gui-style "ZXSpectr" --def-f-function F4 "HardReset" --def-f-function F10 "ExitEmulator" --tbblue-fast-boot-mode --sna-no-change-machine --enable-esxdos-handler --esxdos-root-dir "C:\Spectron2084\sd" "C:\Spectron2084\bin\Spectron2084.sna"
